POSTGRES_CONTAINER ?= postgres-alten
POSTGRES_IMAGE ?= postgres:13
POSTGRES_DB ?= postgres
POSTGRES_PASSWORD ?= azerty789
POSTGRES_BIND_PORT ?= 5432
POSTGRES_BIND ?= -p ${POSTGRES_BIND_PORT}:5432

run_postgres_local:
	docker run -d \
	--name ${POSTGRES_CONTAINER} \
	-e POSTGRES_PASSWORD=${POSTGRES_PASSWORD} \
	-e POSTGRES_DB=${POSTGRES_DB} \
	${POSTGRES_BIND} \
	${POSTGRES_IMAGE}
