# Generated by Django 5.1.2 on 2024-10-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='internalReference',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='shellId',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
